name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run test gcc
      run: gcc -c t1.c
    - name: run test clang
      run: make
  build2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: run test vs
      run: cl -c t1.c
